spring:
  application:
    name: consumer
server:
  port: 8081
  servlet:
    context-path: /consumer

rabbitmq:
  host: 122.51.97.239
  port: 5672
  username: admin
  password: admin
  virtual-host: /