spring:
  profiles:
    active: test
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.97.239:8848
        service: ${spring.application.name}
        namespace: 17c384d5-1096-4a07-9595-5302ceed770d
        metadata:
          version: 1.0
    gateway:
      routes:
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
server:
  port: 5000